
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.LinkedList;
import EventData.*;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.filechooser.*; 
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Wadhwa
 */
public class MainForm extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        closeLbl = new javax.swing.JLabel();
        minimizeLbl = new javax.swing.JPanel();
        minimizel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        startLogo = new javax.swing.JLabel();
        starttxtlbl = new javax.swing.JLabel();
        stoppanel = new javax.swing.JPanel();
        stoplbl = new javax.swing.JLabel();
        stoptxtlbl = new javax.swing.JLabel();
        savePanel = new javax.swing.JPanel();
        savegif = new javax.swing.JLabel();
        savetxtlbl = new javax.swing.JLabel();
        playPanel = new javax.swing.JPanel();
        platgif = new javax.swing.JLabel();
        playtxtlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);
        setResizable(false);

        wrapper.setBackground(new java.awt.Color(175, 145, 100));

        titleBar.setBackground(new java.awt.Color(255, 255, 204));

        closeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.gif"))); // NOI18N
        closeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLblMouseClicked(evt);
            }
        });
        // closeLbl.addKeyListener(new java.awt.event.KeyAdapter() {
        //     public void keyPressed(java.awt.event.KeyEvent evt) {
        //         closeLblKeyPressed(evt);
        //     }
        // });

        minimizeLbl.setBackground(new java.awt.Color(255, 255, 255));

        minimizel.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        minimizel.setText("   -");
        minimizel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelMouseClicked(evt);
            }
        });
        // minimizel.addKeyListener(new java.awt.event.KeyAdapter() {
        //     public void keyPressed(java.awt.event.KeyEvent evt) {
        //         minimizelKeyPressed(evt);
        //     }
        // });

        javax.swing.GroupLayout minimizeLblLayout = new javax.swing.GroupLayout(minimizeLbl);
        minimizeLbl.setLayout(minimizeLblLayout);
        minimizeLblLayout.setHorizontalGroup(
            minimizeLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizeLblLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimizel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        minimizeLblLayout.setVerticalGroup(
            minimizeLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("     Recoed-And-Play");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(minimizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(closeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addComponent(closeLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        startPanel.setBackground(new java.awt.Color(199, 240, 240));
        startPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startPanelMouseClicked(evt);
            }
        });

        startLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/start.gif"))); // NOI18N
        // startLogo.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         startLogoMouseClicked(evt);
        //     }
        // });

        starttxtlbl.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        starttxtlbl.setText("  Start Event Recording");
        // starttxtlbl.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         starttxtlblMouseClicked(evt);
        //     }
        // });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addComponent(starttxtlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(startLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(starttxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        stoppanel.setBackground(new java.awt.Color(46, 204, 113));
        stoppanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stoppanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stoppanelMouseClicked(evt);
            }
        });

        stoplbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playimg.gif"))); // NOI18N

        stoptxtlbl.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        stoptxtlbl.setText("  Stop Event Recording");
        // stoptxtlbl.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         stoptxtlblMouseClicked(evt);
        //     }
        // });

        javax.swing.GroupLayout stoppanelLayout = new javax.swing.GroupLayout(stoppanel);
        stoppanel.setLayout(stoppanelLayout);
        stoppanelLayout.setHorizontalGroup(
            stoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stoppanelLayout.createSequentialGroup()
                .addComponent(stoptxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(stoplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        stoppanelLayout.setVerticalGroup(
            stoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stoplbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stoptxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        savePanel.setBackground(new java.awt.Color(32, 137, 229));
        savePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePanelMouseClicked(evt);
            }
        });

        savegif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saveimg.gif"))); // NOI18N
        // savegif.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         savegifMouseClicked(evt);
        //     }
        // });

        savetxtlbl.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        savetxtlbl.setText("  Save Event Recording");
        // savetxtlbl.addMouseListener(new java.awt.event.MouseAdapter() {
        //     public void mouseClicked(java.awt.event.MouseEvent evt) {
        //         savetxtlblMouseClicked(evt);
        //     }
        // });

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savePanelLayout.createSequentialGroup()
                .addComponent(savetxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(savegif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savegif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(savetxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        playPanel.setBackground(new java.awt.Color(66, 150, 206));
        playPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playPanelMouseClicked(evt);
            }
        });

        platgif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/startimg.gif"))); // NOI18N

        playtxtlbl.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        playtxtlbl.setText("  Play Event Recording");

        javax.swing.GroupLayout playPanelLayout = new javax.swing.GroupLayout(playPanel);
        playPanel.setLayout(playPanelLayout);
        playPanelLayout.setHorizontalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playPanelLayout.createSequentialGroup()
                .addComponent(playtxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(platgif, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        playPanelLayout.setVerticalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(platgif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playtxtlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrapperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stoppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(174, 174, 174))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(startPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(stoppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(playPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseClicked
        // TODO add your handling code here:
        System.out.println("EXIT");
         System.exit(0);
    }//GEN-LAST:event_closeLblMouseClicked

  
    private void minimizelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelMouseClicked
        // TODO add your handling code here:
          this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizelMouseClicked

    private void startPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startPanelMouseClicked
        // TODO add your handling code here:
        try{
            register = new RegisterListeners(list);
             thread = new Thread(register);
            thread.start();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_startPanelMouseClicked

    private void stoppanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stoppanelMouseClicked
        // TODO add your handling code here:
        register.unRegister();
    }//GEN-LAST:event_stoppanelMouseClicked

    private void savePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePanelMouseClicked
        // TODO add your handling code here:
        System.out.println("FINALLYYYYYYYYY");
         JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
        int r = j.showSaveDialog(null); 
        if (r == JFileChooser.APPROVE_OPTION) {
             path = j.getSelectedFile().getAbsolutePath()+".log";
              createObj = new CreateLogFile(list,path);
	      createThread = new Thread(createObj);
	      createThread.start();
        }
        
    }//GEN-LAST:event_savePanelMouseClicked

    private void playPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playPanelMouseClicked
        // TODO add your handling code here:
         System.out.println("HERE OHO");
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
        int r = j.showOpenDialog(null); 
        if (r == JFileChooser.APPROVE_OPTION) {
              playPath = j.getSelectedFile().getAbsolutePath();
              player = new Player(playPath);
              playThread = new Thread(player);
              playThread.start();
              	
    }    	
    }//GEN-LAST:event_playPanelMouseClicked
  


   public void run(){
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-300, dim.height/2-200);
       this.setVisible(true);
   }
    private Player player;
    private String playPath;
    Thread playThread;
    private String path;
    private FileNameExtensionFilter filter;
    private CreateLogFile createObj;
    private Thread createThread;
    private LinkedList<EventData> list = new LinkedList<>();
    private RegisterListeners register;
    private Thread thread;
    private MainForm formObj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel minimizeLbl;
    private javax.swing.JLabel minimizel;
    private javax.swing.JLabel platgif;
    private javax.swing.JPanel playPanel;
    private javax.swing.JLabel playtxtlbl;
    private javax.swing.JPanel savePanel;
    private javax.swing.JLabel savegif;
    private javax.swing.JLabel savetxtlbl;
    private javax.swing.JLabel startLogo;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel starttxtlbl;
    private javax.swing.JLabel stoplbl;
    private javax.swing.JPanel stoppanel;
    private javax.swing.JLabel stoptxtlbl;
    private javax.swing.JPanel titleBar;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
